Device logs
AppiumTestDistribution/AppiumTestDistribution pull request #807
Opened 2020-12-16 12:09 UTC by ShamaUgale

1. Implemented the overloaded methods to support cucumber implementation in TestLogger
2. Added Cucumber listeners and implemented logging to capture device logs for every scenario

2020-12-16 13:31 UTC, SrinivasanTarget requested changes

2020-12-16 13:31 UTC, SrinivasanTarget commented on src/main/java/com/appium/capabilities/Capabilities.java
> +public class Capabilities {
I would rather keep this as-is. Capabilities in the Appium world denotes a different thing altogether.

2020-12-16 13:31 UTC, SrinivasanTarget commented on configs/config.properties
> +FRAMEWORK=cucumber
Please revert it as it might affect our CI runs. Looks like this is an accidental check-in.

2020-12-16 13:31 UTC, SrinivasanTarget commented on src/main/java/com/cucumber/listener/CucumberScenarioListener.java
> +        count=0;
Counter?

2020-12-16 13:31 UTC, SrinivasanTarget commented on src/main/java/com/cucumber/listener/CucumberScenarioListener.java
> +    public void setEventPublisher(EventPublisher eventPublisher){
Checkstyle wont be happy here

2020-12-17 04:11 UTC, saikrishna321 requested changes

2020-12-17 04:11 UTC, saikrishna321 commented on src/main/java/com/appium/manager/TestLogger.java
> +        //setDescription(testName);
Why is this commented out?

2020-12-17 04:11 UTC, saikrishna321 commented on src/main/java/com/appium/manager/TestLogger.java
> +        //stopViewRecording(result, className);
Same here

2020-12-17 04:11 UTC, saikrishna321 commented on src/main/java/com/cucumber/listener/CucumberScenarioListener.java
> +import io.cucumber.plugin.event.*;
Checkstyle won't be happy here

2020-12-17 07:46 UTC, closed without merging